-- MySQL Script generated by MySQL Workbench
-- Sat Nov  7 12:25:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esquema_restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esquema_restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esquema_restaurante` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `esquema_restaurante` ;

-- -----------------------------------------------------
-- Table `esquema_restaurante`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_restaurante`.`clientes` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `pnome` VARCHAR(45) NOT NULL,
  `snome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esquema_restaurante`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_restaurante`.`funcionarios` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `pnome` VARCHAR(45) NOT NULL,
  `snome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(8,2) NOT NULL,
  `data_efetivacao` DATE NOT NULL,
  `gerente_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_funcionario_funcionario1_idx` (`gerente_login` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_funcionario1`
    FOREIGN KEY (`gerente_login`)
    REFERENCES `esquema_restaurante`.`funcionarios` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `funcionario_salario_must_be_positive`
	CHECK((`salario` > 0)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esquema_restaurante`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_restaurante`.`estoque` (
  `idEstoque` INT NOT NULL,
  `funcionario_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoque`),
  INDEX `fk_estoque_funcionario1_idx` (`funcionario_login` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_funcionario1`
    FOREIGN KEY (`funcionario_login`)
    REFERENCES `esquema_restaurante`.`funcionarios` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esquema_restaurante`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_restaurante`.`pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `comanda` INT NULL DEFAULT NULL,
  `cliente_login` VARCHAR(45) NULL,
  `funcionario_login` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente_login` ASC) VISIBLE,
  INDEX `fk_pedido_funcionario1_idx` (`funcionario_login` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_login`)
    REFERENCES `esquema_restaurante`.`clientes` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_funcionario1`
    FOREIGN KEY (`funcionario_login`)
    REFERENCES `esquema_restaurante`.`funcionarios` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esquema_restaurante`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_restaurante`.`produtos` (
  `idProduto` INT NOT NULL,
  `prod_idEstoque` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor_de_compra` DOUBLE NOT NULL,
  `valor_de_venda` DOUBLE NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_produtos_estoque1_idx` (`prod_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_estoque1`
    FOREIGN KEY (`prod_idEstoque`)
    REFERENCES `esquema_restaurante`.`estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `valor_de_compra_must_be_positive`
	CHECK((`valor_de_compra` >= 0)),
  CONSTRAINT `valor_de_venda_must_be_positive`
	CHECK((`valor_de_venda` >= 0)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esquema_restaurante`.`produtos_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_restaurante`.`produtos_pedidos` (
  `pedido_idPedido` INT NOT NULL,
  `produto_idProduto` INT NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `qtd` INT NOT NULL,
  `observacao` VARCHAR(45) NULL,
  PRIMARY KEY (`pedido_idPedido`, `produto_idProduto`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_idProduto` ASC) VISIBLE,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `esquema_restaurante`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `esquema_restaurante`.`produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prod_pedido_valor_must_be_positive`
	CHECK((`valor` >= 0)),
  CONSTRAINT `prod_pedido_qtd_must_be_positive`
	CHECK((`qtd` >= 0)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `esquema_restaurante`.`Atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_restaurante`.`Atendimentos` (
  `idAtendimento` INT NOT NULL AUTO_INCREMENT,
  `inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fim` TIMESTAMP NULL,
  `atend_idPedido` INT NOT NULL,
  `atend_idProduto` INT NOT NULL,
  PRIMARY KEY (`idAtendimento`, `atend_idPedido`, `atend_idProduto`),
  UNIQUE INDEX `idAtendimento_UNIQUE` (`idAtendimento` ASC) VISIBLE,
  INDEX `fk_Atendimento_pedido_solicita_produto1_idx` (`atend_idPedido` ASC, `atend_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Atendimento_pedido_solicita_produto1`
    FOREIGN KEY (`atend_idPedido` , `atend_idProduto`)
    REFERENCES `esquema_restaurante`.`produtos_pedidos` (`pedido_idPedido` , `produto_idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
